# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcc310bf05cc400227ea26465759c68a8fb349bec5b4fee31e98d70cfa05e45ad839864a9604d56c3f32b1f78567d3449a46923f000b5b0610004958ccdebb91

test:
  secret_key_base: 8a62b95983d4ffbd8f8e9525aa3b42cf605f2bda281ffef1ff393d68e851dcd6d8fd8bce90a4b733563ba418460ed8cc8611c91d397e322f0b9c2b8a1d4fb08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
